# Generated by Django 6.0.5 on 2026-05-19 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_num', models.IntegerField()),
                ('date', models.DateField()),
                ('proforma_number', models.IntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ADVANCE',
            },
        ),
        migrations.CreateModel(
            name='AdvanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_movement', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trips_quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='advances.advance')),
            ],
            options={
                'db_table': 'ADVANCE_MOVEMENT',
            },
        ),
    ]
