# Generated by Django 6.0.5 on 2026-09-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='expected_trips_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        # NOTA: makemigrations también propuso un AlterField de 'id' en
        # Advance/AdvanceMovement (BigAutoField -> AutoField) por un desfase
        # preexistente entre el historial de migraciones y los modelos
        # (nada relacionado con este feature) — se deja fuera a propósito
        # para no tocar el tipo de columna del PK en producción sin que
        # nadie lo haya pedido explícitamente.
    ]
