# Generated by Django 6.0.5 on 2026-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_trips', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_transfer', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_advance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_trip_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'DAILY_SUMMARY',
            },
        ),
    ]
