# Generated by Django 6.0.5 on 2026-06-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0001_initial'),
        ('masters', '0003_remove_paymentmethod_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='income_advance',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='income_cash',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='income_transfer',
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_trips',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DailySummaryPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.paymentmethod')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_details', to='cash_closing.dailysummary')),
            ],
            options={
                'db_table': 'DAILY_SUMMARY_PAYMENT',
            },
        ),
    ]
