# Generated by Django 6.0.5 on 2026-08-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0002_remove_dailysummary_income_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='state',
            field=models.CharField(choices=[('closed', 'Cerrado'), ('reverted', 'Revertido')], default='closed', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
