# Generated by Django 6.0.5 on 2026-05-19 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'MATERIAL_TYPE',
            },
        ),
        migrations.CreateModel(
            name='OriginSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ORIGIN_SITE',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_advance', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PAYMENT_METHOD',
            },
        ),
        migrations.CreateModel(
            name='PinsDumper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiental_pin', models.CharField(max_length=30)),
                ('propietary', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.CharField(max_length=20)),
                ('plaque', models.CharField(max_length=6)),
                ('expedition_site', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver', models.CharField(max_length=50)),
                ('date_register', models.DateField()),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PINS_DUMPERS',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'VEHICLE_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=6, unique=True)),
                ('dumper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masters.pinsdumper')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.vehicletype')),
            ],
            options={
                'db_table': 'VEHICLE',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masters.materialtype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.vehicletype')),
            ],
            options={
                'db_table': 'TARIFF',
            },
        ),
    ]
