# Generated by Django 6.0.5 on 2026-06-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_paymentmethod_type_alter_materialtype_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='type',
        ),
    ]
