# Generated by Django 6.0.5 on 2026-07-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_paymentmethod_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CITY',
            },
        ),
    ]
