# Generated by Django 6.0.5 on 2026-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinsdumper',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='ambiental_pin',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='driver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='expedition_site',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pinsdumper',
            name='plaque',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
