# Generated by Django 6.0.5 on 2026-08-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
