# Generated by Django 6.0.5 on 2026-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('superuser', 'Superusuario'), ('commercial_admin', 'Administrador Comercial'), ('cashier', 'Operador de Caja'), ('accountant', 'Contador'), ('auditor', 'Auditor')], max_length=30)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"USER"',
            },
        ),
    ]
