# Generated by Django 6.0.5 on 2026-08-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Nota: Django también propuso un AlterField sobre 'id' (drift de
        # estado de migraciones preexistente, sin relación con 8A.4 — el
        # campo ya era AutoField(primary_key=True) en el modelo). Se omite
        # a propósito para no mezclar un cambio no pedido con este fix.
    ]
