# Generated by Django 6.0.5 on 2026-09-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('commercial_admin', 'Administrador Comercial'), ('cashier', 'Operador de Caja'), ('accountant', 'Contador'), ('auditor', 'Auditor'), ('certifier', 'Certificador'), ('viewer', 'Consulta')], max_length=30),
        ),
    ]
