# Generated by Django 6.0.5 on 2026-08-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('annul', 'Anulación'), ('access_denied', 'Acceso denegado'), ('revert', 'Reversión de cierre de caja'), ('recalculo_cierre', 'Recálculo automático de cierre de caja')], max_length=20),
        ),
    ]
