# Generated by Django 6.0.5 on 2026-08-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('annul', 'Anulación'), ('access_denied', 'Acceso denegado'), ('revert', 'Reversión de cierre de caja'), ('recalculo_cierre', 'Recálculo automático de cierre de caja'), ('login_failed', 'Intento fallido de inicio de sesión'), ('account_locked', 'Cuenta bloqueada temporalmente por intentos fallidos')], max_length=20),
        ),
    ]
