# Generated by Django 6.0.5 on 2026-05-19 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0001_initial'),
        ('cash_closing', '0001_initial'),
        ('clients', '0001_initial'),
        ('invoices', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_num', models.IntegerField(unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extern_voucher_num', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_pos', models.IntegerField(blank=True, null=True)),
                ('date_register', models.DateField()),
                ('date', models.DateField()),
                ('certification_state', models.BooleanField(blank=True, null=True)),
                ('certification_num', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.BooleanField(default=True)),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='advances.advance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invoices.invoice')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.materialtype')),
                ('origin_site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.originsite')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.paymentmethod')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cash_closing.dailysummary')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.vehicle')),
            ],
            options={
                'db_table': 'TRIP',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trips.trip')),
            ],
            options={
                'db_table': 'TRANSFER',
            },
        ),
    ]
