# Generated by Django 6.0.5 on 2026-07-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_id_delete_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_register',
            field=models.DateTimeField(),
        ),
    ]
