# Generated by Django 6.0.5 on 2026-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_change_date_register_to_datetimefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pending_debt_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
