# Generated by Django 6.0.5 on 2026-09-15 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('trips', '0005_trip_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='certification_num',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='certification_state',
        ),
        migrations.AddField(
            model_name='trip',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='trip',
            name='certificate_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
