# Generated by Django 6.0.5 on 2026-09-13 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0004_backfill_expected_trips_quantity'),
        ('clients', '0004_client_city_finalize'),
        ('masters', '0005_relax_pinsdumper_import_fields'),
        ('trips', '0005_trip_observations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('advance', 'Anticipo'), ('transfer', 'Transferencia')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('executed', 'Ejecutado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executed_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='advances.advance')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executed_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='trips.trip')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masters.paymentmethod')),
            ],
            options={
                'db_table': 'PENDING_ENTRY',
            },
        ),
    ]
