# Generated by Django 6.0.5 on 2026-09-13 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0003_advance_expected_trips_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCountClosure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('close', 'Cerrar'), ('undo_close', 'Deshacer cierre'), ('reopen', 'Reabrir')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='advances.advance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PHYSICAL_COUNT_CLOSURE',
            },
        ),
        migrations.CreateModel(
            name='PhysicalCountEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='advances.advance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PHYSICAL_COUNT_ENTRY',
            },
        ),
    ]
