# Generated by Django 6.0.5 on 2026-05-19 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abrev_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('facturation_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('validate_certification', models.BooleanField(null=True)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLIENT',
            },
        ),
    ]
