"""
Django settings for sigmo_backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# 9.4: antes hardcodeado en []. Con DEBUG=False (correcto en producción)
# eso rechaza TODAS las requests (Django exige que el Host: de la request
# esté en esta lista), lo que tienta a "arreglarlo" dejando DEBUG=True en
# producción — reabriendo la exposición de información sensible (stack
# traces, variables de entorno) que ya se cerró en la fase de contención
# del .env. Se lee de una variable de entorno separada por comas, mismo
# patrón que SECRET_KEY/DB_* arriba; en local, si no está definida, cae al
# valor de desarrollo de siempre.
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    # Apps propias
    'apps.common',
    'apps.users',
    'apps.clients',
    'apps.masters',
    'apps.trips',
    'apps.advances',
    'apps.expenses',
    'apps.invoices',
    'apps.cash_closing',
    'apps.reports',
    'apps.audit',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # BUG 3: ActiveUserJWTAuthentication añade el chequeo de
        # User.state que la clase estándar de simplejwt nunca aplica en
        # este proyecto (ver docstring en apps/users/authentication.py).
        'apps.users.authentication.ActiveUserJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigmo_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigmo_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Mismo patrón que ALLOWED_HOSTS: hardcodeado a localhost rompía toda
# petición del frontend en producción (bloqueo CORS silencioso — el
# navegador ni siquiera muestra el error real en la mayoría de los casos).
# Se lee de env, separado por comas, con el valor de desarrollo como
# fallback si no está definida.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',') if o.strip()
]

SIMPLE_JWT = {
    # Token de acceso: el que usas en cada request
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),  # RF-06B: máximo 8 horas
    
    # Token de refresco: para obtener un nuevo access token sin hacer login
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    
    'ROTATE_REFRESH_TOKENS': True,  # Genera nuevo refresh token cada vez que lo usas
    'BLACKLIST_AFTER_ROTATION': False,
    
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'Documentación Endpoints SIGMO',
    'DESCRIPTION': 'Documentación automatizada de los endpoints de mi proyecto.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Sin esto, `collectstatic` no tiene dónde escribir y el admin de Django
# queda sin estilos en producción (DEBUG=False apaga el servido de
# estáticos que Django usa solo en desarrollo).
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'users.User'

# Endurecimiento HTTPS: apagado por defecto (False/0) para no romper el
# acceso si el servidor de producción todavía no tiene HTTPS terminado ahí
# (redirects en bucle, cookies que el navegador descarta). Se activa
# explícitamente vía env una vez el dominio de producción ya sirve HTTPS.
# Mismo patrón que DEBUG/ALLOWED_HOSTS/CORS_ALLOWED_ORIGINS arriba.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Configuración de intentos de login (RF-03)
LOGIN_MAX_ATTEMPTS = 10
LOGIN_LOCKOUT_MINUTES = 15